apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kusalthiwanka/backend-node:latest
          ports:
            - containerPort: 5000 # Updated port
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # Updated port
      targetPort: 5000 # Updated port
  clusterIP: None
  